name: task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fpdart: ^1.1.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.6
  date_time_picker_ultra: ^0.0.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

